project:
  type: website
  output-dir: docs

website:
  title: "Jesus Gonzalez"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



