project:
  type: website
  output-dir: docs
  resources: 
    - CNAME 

website:
  title: "Jesus Gonzalez"
  google-analytics: 
    tracking-id: G-B730JHHC8P
    storage: cookies
    anonymize-ip: false
  cookie-consent:
    style: interstitial
    palette: dark
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
